use chrono::Utc;use rusqlite::{params,Connection};use serde::{Deserialize,Serialize};use std::sync::Mutex;use tauri::{menu::{Menu,MenuItem},tray::TrayIconBuilder,Emitter,Manager,State,WindowEvent};use tauri_plugin_autostart::MacosLauncher;

const API:&str="http://localhost:8000/api/v1";
#[derive(Debug,Serialize,Deserialize,Clone)]struct Session{access_token:String,refresh_token:String,expires_at:i64}
#[derive(Debug,Serialize,Deserialize,Clone)]struct Occurrence{id:String,reminder_id:String,title:String,description:Option<String>,#[serde(rename="type")]kind:String,priority:String,scheduled_date:String,scheduled_at:String,due_at:String,status:String,snoozed_until:Option<String>,completed_at:Option<String>,updated_at:String}
#[derive(Debug,Serialize,Deserialize)]struct Page{items:Vec<Occurrence>,next_cursor:Option<String>}
struct Db(Mutex<Connection>);
fn migrate(c:&Connection)->rusqlite::Result<()>{c.execute_batch("CREATE TABLE IF NOT EXISTS occurrences(id TEXT PRIMARY KEY,payload TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS outbox(id TEXT PRIMARY KEY,kind TEXT NOT NULL,occurrence_id TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS sync_state(key TEXT PRIMARY KEY,value TEXT NOT NULL);")}
fn cache(c:&Connection,items:&[Occurrence])->Result<(),String>{let tx=c.unchecked_transaction().map_err(|e|e.to_string())?;for item in items{tx.execute("INSERT INTO occurrences(id,payload,updated_at) VALUES(?1,?2,?3) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at",params![item.id,serde_json::to_string(item).unwrap(),item.updated_at]).map_err(|e|e.to_string())?;}tx.commit().map_err(|e|e.to_string())}
#[tauri::command]fn save_session(value:Session)->Result<(),String>{keyring::Entry::new("reminder-desktop","session").map_err(|e|e.to_string())?.set_password(&serde_json::to_string(&value).unwrap()).map_err(|e|e.to_string())}
#[tauri::command]fn load_session()->Result<Option<Session>,String>{match keyring::Entry::new("reminder-desktop","session").map_err(|e|e.to_string())?.get_password(){Ok(v)=>Ok(serde_json::from_str(&v).ok()),Err(keyring::Error::NoEntry)=>Ok(None),Err(e)=>Err(e.to_string())}}
#[tauri::command]fn clear_session()->Result<(),String>{keyring::Entry::new("reminder-desktop","session").map_err(|e|e.to_string())?.delete_credential().map_err(|e|e.to_string())}
#[tauri::command]fn list_cached(db:State<Db>)->Result<Vec<Occurrence>,String>{let c=db.0.lock().unwrap();let mut s=c.prepare("SELECT payload FROM occurrences ORDER BY updated_at").map_err(|e|e.to_string())?;let rows=s.query_map([],|r|r.get::<_,String>(0)).map_err(|e|e.to_string())?;Ok(rows.filter_map(|x|x.ok().and_then(|v|serde_json::from_str(&v).ok())).collect())}
async fn send_action(id:&str,path:&str,body:serde_json::Value,s:&Session)->Result<Occurrence,String>{reqwest::Client::new().post(format!("{API}/reminder-occurrences/{id}/{path}")).bearer_auth(&s.access_token).json(&body).send().await.map_err(|e|e.to_string())?.error_for_status().map_err(|e|e.to_string())?.json().await.map_err(|e|e.to_string())}
fn enqueue(c:&Connection,kind:&str,id:&str,payload:&serde_json::Value)->Result<(),String>{c.execute("INSERT INTO outbox(id,kind,occurrence_id,payload,created_at) VALUES(?1,?2,?3,?4,?5)",params![uuid::Uuid::new_v4().to_string(),kind,id,payload.to_string(),Utc::now().to_rfc3339()]).map_err(|e|e.to_string())?;Ok(())}
async fn flush_outbox(c:&Connection,s:&Session)->Result<(),String>{let pending={let mut q=c.prepare("SELECT id,kind,occurrence_id,payload FROM outbox ORDER BY created_at").map_err(|e|e.to_string())?;q.query_map([],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?))).map_err(|e|e.to_string())?.filter_map(Result::ok).collect::<Vec<_>>()};for(row_id,kind,id,payload)in pending{let value:serde_json::Value=serde_json::from_str(&payload).unwrap_or_default();match send_action(&id,&kind,value,s).await{Ok(item)=>{cache(c,&[item])?;c.execute("DELETE FROM outbox WHERE id=?1",[row_id]).map_err(|e|e.to_string())?},Err(_)=>{c.execute("UPDATE outbox SET attempts=attempts+1 WHERE id=?1",[row_id]).map_err(|e|e.to_string())?;break}}}Ok(())}
#[tauri::command]async fn sync_now(session:Session,db:State<'_,Db>)->Result<Vec<Occurrence>,String>{flush_outbox(&db.0.lock().unwrap(),&session).await?;let page:Page=reqwest::Client::new().get(format!("{API}/me/reminders")).bearer_auth(session.access_token).send().await.map_err(|e|e.to_string())?.error_for_status().map_err(|e|e.to_string())?.json().await.map_err(|e|e.to_string())?;cache(&db.0.lock().unwrap(),&page.items)?;Ok(page.items)}
#[tauri::command]async fn complete_occurrence(id:String,session:Session,db:State<'_,Db>)->Result<(),String>{match send_action(&id,"complete",serde_json::json!({}),&session).await{Ok(item)=>cache(&db.0.lock().unwrap(),&[item]),Err(_)=>enqueue(&db.0.lock().unwrap(),"complete",&id,&serde_json::json!({}))}}
#[tauri::command]async fn snooze_occurrence(id:String,minutes:i32,session:Session,db:State<'_,Db>)->Result<(),String>{let body=serde_json::json!({"minutes":minutes});match send_action(&id,"snooze",body.clone(),&session).await{Ok(item)=>cache(&db.0.lock().unwrap(),&[item]),Err(_)=>enqueue(&db.0.lock().unwrap(),"snooze",&id,&body)}}
#[tauri::command]fn hide_main_window(app:tauri::AppHandle){if let Some(w)=app.get_webview_window("main"){let _=w.hide();}}
#[tauri::command]fn enable_autostart(app:tauri::AppHandle)->Result<(),String>{use tauri_plugin_autostart::ManagerExt;app.autolaunch().enable().map_err(|e|e.to_string())}
#[tauri::command]fn logout(app:tauri::AppHandle)->Result<(),String>{let _=clear_session();if let Some(w)=app.get_webview_window("main"){let _=w.show();}Ok(())}
pub fn run(){tauri::Builder::default().plugin(tauri_plugin_notification::init()).plugin(tauri_plugin_autostart::init(MacosLauncher::LaunchAgent,Some(vec!["--minimized"]))).setup(|app|{let data=app.path().app_data_dir()?;std::fs::create_dir_all(&data)?;let c=Connection::open(data.join("cache.sqlite3"))?;migrate(&c)?;app.manage(Db(Mutex::new(c)));let open=MenuItem::with_id(app,"open","Open Reminders",true,None::<&str>)?;let sync=MenuItem::with_id(app,"sync","Sync Now",true,None::<&str>)?;let logout=MenuItem::with_id(app,"logout","Logout",true,None::<&str>)?;let exit=MenuItem::with_id(app,"exit","Exit",true,None::<&str>)?;let menu=Menu::with_items(app,&[&open,&sync,&logout,&exit])?;TrayIconBuilder::new().menu(&menu).on_menu_event(|app,e|match e.id.as_ref(){"open"=>{if let Some(w)=app.get_webview_window("main"){let _=w.show();let _=w.set_focus();}},"sync"=>{let _=app.emit("sync-requested",());},"logout"=>{let _=clear_session();let _=app.emit("logged-out",());if let Some(w)=app.get_webview_window("main"){let _=w.show();}},"exit"=>app.exit(0),_=>{}}).build(app)?;if !std::env::args().any(|a|a=="--minimized"){app.get_webview_window("main").unwrap().show()?;}Ok(())}).on_window_event(|window,event|if let WindowEvent::CloseRequested{api,..}=event{api.prevent_close();let _=window.hide();}).invoke_handler(tauri::generate_handler![save_session,load_session,clear_session,list_cached,sync_now,complete_occurrence,snooze_occurrence,hide_main_window,enable_autostart,logout]).run(tauri::generate_context!()).expect("desktop runtime failed")}

#[cfg(test)]mod tests{use super::*;#[test]fn migrations_are_idempotent(){let c=Connection::open_in_memory().unwrap();migrate(&c).unwrap();migrate(&c).unwrap();let n:i64=c.query_row("SELECT count(*) FROM sqlite_master WHERE type='table'",[],|r|r.get(0)).unwrap();assert!(n>=3);}}
