"use client";
import Link from "next/link";
import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Plus} from "lucide-react";
import {AppShell} from "@/components/app-shell";
import {Empty,Status} from "@/components/status";
import {api,queries} from "@/lib/api";
import type {Reminder} from "@/lib/types";

export default function Reminders(){const qc=useQueryClient();const [assigning,setAssigning]=useState<Reminder|null>(null);const list=useQuery({queryKey:["reminders"],queryFn:queries.reminders});const toggle=useMutation({mutationFn:({id,on}:{id:string;on:boolean})=>api(`/reminders/${id}/${on?"enable":"disable"}`,{method:"POST"}),onSuccess:()=>qc.invalidateQueries({queryKey:["reminders"]})});const remove=useMutation({mutationFn:(id:string)=>api(`/reminders/${id}`,{method:"DELETE"}),onSuccess:()=>qc.invalidateQueries({queryKey:["reminders"]})});return <AppShell title="Reminders" subtitle="Manage recurring assignments and schedules." action={<Link href="/reminders/new" className="btn btn-primary flex gap-2"><Plus size={18}/>New reminder</Link>}>{list.data?.items.length?<div className="card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#f3f7f4] text-left"><tr>{["Title","Type","Assigned","Time","Status","Priority","Actions"].map(x=><th key={x} className="px-5 py-3">{x}</th>)}</tr></thead><tbody>{list.data.items.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="px-5 py-4 font-medium">{r.title}</td><td className="px-5 py-4">{r.type}</td><td className="px-5 py-4">{r.assigned_user_ids.length}</td><td className="px-5 py-4">{r.reminder_time.slice(0,5)}</td><td className="px-5 py-4"><Status active={r.is_active}/></td><td className="px-5 py-4">{r.priority}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-3"><button className="text-blue-700 font-bold" onClick={()=>setAssigning(r)}>Add members</button><button className="text-emerald-700 font-bold" onClick={()=>toggle.mutate({id:r.id,on:!r.is_active})}>{r.is_active?"Disable":"Enable"}</button><button className="text-red-700 font-bold" onClick={()=>{if(confirm(`Delete ${r.title}? History will be preserved.`))remove.mutate(r.id)}}>Delete</button></div></td></tr>)}</tbody></table></div>:<Empty message={list.isLoading?"Loading reminders…":"No reminders have been created."}/>} {assigning&&<AssignMembers reminder={assigning} close={()=>setAssigning(null)}/>}</AppShell>}

function AssignMembers({reminder,close}:{reminder:Reminder;close:()=>void}){const qc=useQueryClient();const members=useQuery({queryKey:["members","assign"],queryFn:()=>queries.members("","true")});const add=useMutation({mutationFn:(ids:string[])=>api(`/reminders/${reminder.id}/assignments`,{method:"POST",body:JSON.stringify({user_ids:ids})}),onSuccess:()=>{qc.invalidateQueries({queryKey:["reminders"]});close()}});const available=members.data?.items.filter(m=>!reminder.assigned_user_ids.includes(m.id))??[];return <div className="fixed inset-0 bg-black/35 grid place-items-center p-4 z-50"><form className="card w-full max-w-lg p-6" onSubmit={e=>{e.preventDefault();add.mutate(new FormData(e.currentTarget).getAll("user_ids").map(String))}}><h2 className="text-xl font-semibold">Add members to {reminder.title}</h2><p className="muted text-sm mt-1 mb-5">Existing assignments and history remain unchanged.</p><select name="user_ids" multiple required className="field min-h-48">{available.map(m=><option key={m.id} value={m.id}>{m.name} — {m.email}</option>)}</select>{add.error&&<p className="text-red-700 text-sm mt-3">{add.error.message}</p>}<div className="flex justify-end gap-3 mt-6"><button type="button" className="btn btn-secondary" onClick={close}>Cancel</button><button disabled={!available.length||add.isPending} className="btn btn-primary">Add selected</button></div></form></div>}
